### ISSUE TITLE
Thập - Assessment #2

### ISSUE THREAD

**Issue by longhypepoly** [hypepoly-internship-2022/thi-thap-assessment-2#1]

**Comment by longhypepoly** [comment]
@Dangthap - Em xem lại thử có quên commit file gì lên ko nhé, hiện tại anh play ko được, em xem warning message ở hình dưới

![Image](https://user-images.githubusercontent.com/116874636/201876571-5d8fa447-0d88-4dc2-9856-6dcfeefb4e72.png)

**Comment by Dangthap** [comment]
Em mới commit lại, anh play lại giúp em.

Vào Th 3, 15 thg 11, 2022 vào lúc 16:03 Long Tran <
***@***.***> đã viết:

**Comment by longhypepoly** [comment]
Em cho nó chạy trên mặt phẳng của quad như yêu cầu nhé 😉

**Comment by longhypepoly** [comment]
Good job 💯
